In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("house_price.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'house_price.csv'

In [ ]:
df

,Bedrooms,Bathrooms,Area_sqft,Location,Price
0,2,1.0,800.0,Urban,2500000.0
1,3,2.0,1200.0,Urban,4200000.0
2,4,3.0,1800.0,Urban,6500000.0
3,2,2.0,950.0,Suburban,2800000.0
4,3,2.0,1300.0,Suburban,4500000.0
...,...,...,...,...,...
95,2,1.0,800.0,Urban,2500000.0
96,2,1.0,800.0,urban,2500000.0
97,1,1.0,600.0,Rural,1800000.0
98,2,1.0,850.0,Rural,2200000.0


In [ ]:
df

,Bedrooms,Bathrooms,Area_sqft,Location,Price
0,2,1.0,800.0,Urban,2500000.0
1,3,2.0,1200.0,Urban,4200000.0
2,4,3.0,1800.0,Urban,6500000.0
3,2,2.0,950.0,Suburban,2800000.0
4,3,2.0,1300.0,Suburban,4500000.0
...,...,...,...,...,...
95,2,1.0,800.0,Urban,2500000.0
96,2,1.0,800.0,urban,2500000.0
97,1,1.0,600.0,Rural,1800000.0
98,2,1.0,850.0,Rural,2200000.0


In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Bedrooms   100 non-null    int64  
 1   Bathrooms  98 non-null     float64
 2   Area_sqft  95 non-null     float64
 3   Location   98 non-null     str    
 4   Price      98 non-null     float64
dtypes: float64(3), int64(1), str(1)
memory usage: 4.0 KB


In [ ]:
df.shape

NameError: name 'df' is not defined

In [ ]:

df["Bedrooms"] = df["Bedrooms"].fillna(df["Bedrooms"].mean())
df["Bathrooms"] = df["Bathrooms"].fillna(df["Bathrooms"].mean())
df["Area_sqft"] = df["Area_sqft"].fillna(df["Area_sqft"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())


In [ ]:
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["Location"] = encoder.fit_transform(df["Location"])

In [ ]:
print(df.isnull().sum())
print(df.head())

Bedrooms     0
Bathrooms    0
Area_sqft    0
Location     0
Price        0
dtype: int64
   Bedrooms  Bathrooms  Area_sqft  Location      Price
0         2        1.0      800.0         5  2500000.0
1         3        2.0     1200.0         5  4200000.0
2         4        3.0     1800.0         5  6500000.0
3         2        2.0      950.0         3  2800000.0
4         3        2.0     1300.0         3  4500000.0


In [ ]:
X = df.drop(columns=["Price"])
y = df['Price']

In [ ]:
X

,Bedrooms,Bathrooms,Area_sqft,Location
0,2,1.0,800.0,5
1,3,2.0,1200.0,5
2,4,3.0,1800.0,5
3,2,2.0,950.0,3
4,3,2.0,1300.0,3
...,...,...,...,...
95,2,1.0,800.0,5
96,2,1.0,800.0,6
97,1,1.0,600.0,2
98,2,1.0,850.0,2


In [ ]:
y

0     2500000.0
1     4200000.0
2     6500000.0
3     2800000.0
4     4500000.0
        ...    
95    2500000.0
96    2500000.0
97    1800000.0
98    2200000.0
99    4800000.0
Name: Price, Length: 100, dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

In [ ]:
X_train

,Bedrooms,Bathrooms,Area_sqft,Location
55,4,3.0,1452.105263,5
88,2,1.0,850.000000,2
26,5,4.0,2500.000000,5
42,4,3.0,1800.000000,5
69,3,2.0,1400.000000,3
...,...,...,...,...
60,2,1.0,800.000000,5
71,3,2.0,1200.000000,5
14,3,2.0,1300.000000,3
92,4,3.0,1452.105263,5


In [ ]:
y_train

55    7000000.0
88    2200000.0
26    9500000.0
42    6500000.0
69    4800000.0
        ...    
60    2500000.0
71    4200000.0
14    4500000.0
92    6500000.0
51    4200000.0
Name: Price, Length: 80, dtype: float64

In [ ]:
X_test

,Bedrooms,Bathrooms,Area_sqft,Location
83,2,2.0,950.000000,3
53,2,2.0,950.000000,3
70,2,1.0,800.000000,5
45,4,3.0,2000.000000,5
44,3,2.0,1300.000000,3
39,3,2.0,1400.000000,3
22,4,3.0,1800.000000,0
80,2,1.0,800.000000,5
10,2,1.0,800.000000,5
0,2,1.0,800.000000,5


In [ ]:
y_test

83     2800000.0
53     2800000.0
70     2500000.0
45     7000000.0
44     4500000.0
39     4800000.0
22     6500000.0
80     2500000.0
10     2500000.0
0      2500000.0
18     2200000.0
30     2500000.0
73     2800000.0
33     2800000.0
90    60000000.0
4      4500000.0
76     9500000.0
77     1800000.0
12     6500000.0
31     4200000.0
Name: Price, dtype: float64

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["Location"] = encoder.fit_transform(df["Location"])

In [ ]:
X = df[["Bedrooms", "Bathrooms", "Area_sqft", "Location"]]
y = df["Price"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.95202863,  0.94213008,  0.20420248,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.88748576, -1.30650408],
       [ 1.82745726,  2.02105205,  2.10415989,  0.9493303 ],
       [ 0.95202863,  0.94213008,  0.83497689,  0.9493303 ],
       [ 0.07660001, -0.13679189,  0.10972946, -0.55455929],
       [ 0.95202863,  0.94213008,  1.1976006 ,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.97814168,  1.7012751 ],
       [ 0.07660001, -0.13679189,  0.10972946, -0.55455929],
       [ 0.95202863,  0.94213008,  0.83497689,  0.9493303 ],
       [ 0.07660001, -0.13679189, -0.25289426,  0.9493303 ],
       [-1.67425725, -1.21571386, -1.3407654 , -1.30650408],
       [ 0.95202863,  0.94213008,  1.1976006 ,  0.9493303 ],
       [-0.79882862, -0.05972604, -0.88748576, -1.30650408],
       [-0.79882862, -0.13679189, -0.7061739 , -0.55455929],
       [ 0.95202863,  0.94213008,  0.20420248,  0.9493303 ],
       [ 1.82745726,  2.

In [ ]:
X_test

array([[-0.79882862, -0.13679189, -0.7061739 , -0.55455929],
       [-0.79882862, -0.13679189, -0.7061739 , -0.55455929],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [ 0.95202863,  0.94213008,  1.1976006 ,  0.9493303 ],
       [ 0.07660001, -0.13679189, -0.0715824 , -0.55455929],
       [ 0.07660001, -0.13679189,  0.10972946, -0.55455929],
       [ 0.95202863,  0.94213008,  0.83497689, -2.81039367],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [-0.79882862, -1.21571386, -0.88748576, -1.30650408],
       [-0.79882862, -1.21571386, -0.97814168,  0.9493303 ],
       [-0.79882862, -0.13679189, -0.7061739 , -0.55455929],
       [-0.79882862, -0.13679189,  0.20420248, -0.55455929],
       [-0.79882862, -1.21571386, 24.76814203,  0.9493303 ],
       [ 0.07660001, -0.13679189, -0.0715824 , -0.55455929],
       [ 1.82745726,  2.

In [ ]:
model = LinearRegression()

In [ ]:
model

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [ ]:
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](4,)","[908006.76,560916.03,837008.06, 76258.44]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,4.631e+06
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,4
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(4)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](4,)","[16.44, 6.44, 2.18, 1.85]"


In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([ 3195994.94242403,  3195994.94242403,  2477855.3545309 ,
        7099128.67648828,  4522048.25979056,  4673807.74631174,
        6508899.03045131,  2477855.3545309 ,  2477855.3545309 ,
        2477855.3545309 ,  2381708.69399472,  2477855.3545309 ,
        3195994.94242403,  3957987.31158826, 24027702.44053822,
        4522048.25979056,  9258005.85094579,  1207414.86314936,
        6795609.70344592,  4484973.04246723])

In [ ]:
df.tail(1)

,Bedrooms,Bathrooms,Area_sqft,Location,Price
99,3,2.0,1400.0,3,4800000.0


In [ ]:
test_new = [[1800, 6]]

In [ ]:


result = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

print(result.head())

   Actual Price  Predicted Price
0     2800000.0     3.195995e+06
1     2800000.0     3.195995e+06
2     2500000.0     2.477855e+06
3     7000000.0     7.099129e+06
4     4500000.0     4.522048e+06


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [ ]:
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))

MAE : 2015209.0065844667
MSE : 64822907387378.81
RMSE : 8051267.43981212
R2 Score : 0.5765516875939598


In [ ]:
new_house = pd.DataFrame({
    "Bedrooms": [3],
    "Bathrooms": [2],
    "Area_sqft": [1500],
    "Location": ["Urban"]
})

In [ ]:
print(encoder.classes_)

[0 1 2 3 4 5 6]


In [ ]:
df=pd.read_csv("house_price.csv")

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["Location"] = encoder.fit_transform(df["Location"])

In [ ]:
print(encoder.classes_)

[' suburban ' 'RURAL' 'Rural' 'Suburban' 'URBAN' 'Urban' 'urban' nan]


In [ ]:
new_house["Location"] = encoder.transform(new_house["Location"])

In [ ]:
new_house = scaler.transform(new_house)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [ ]:
predicted_price = model.predict(new_house)

print("Predicted House Price:", predicted_price[0])

Predicted House Price: 1264370669.2615426


In [ ]:
import joblib

joblib.dump(model, "house_price_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoder, "encoder.pkl")

['encoder.pkl']

project me kya-kya hua?
✅ Dataset load kiya
✅ Missing values check ki
✅ Categorical data (Location) encode kiya
✅ Data split kiya
✅ Feature scaling ki
✅ Linear Regression model train kiya
✅ Prediction ki
✅ Accuracy (MAE, MSE, RMSE, R² Score) check ki
✅ Naye house ki price predict ki
✅ Model save kiya